substitutions:
  _PROJECT_ID: 'your-project-id'  # Replace with placeholder

steps:
- name: 'gcr.io/cloud-builders/python38'
  args: ['pip', 'install', '-r', 'requirements.txt']

- name: 'gcr.io/cloud-builders/pack'  # Cloud Build Pack for Streamlit
  args: ['--path', '.']

images: ['gcr.io/$_PROJECT_ID/medbot:latest']
